remote_theme : mmistakes/minimal-mistakes
# the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url                      : "https://readme-finnq.github.io" 
# the subpath of your site, e.g. "/blog"
baseurl                  : "" 
